name: Build SDL3 so

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkput
      uses: actions/checkout@v3
    
#    - name: Set output date as output variable
#      id: output-date
#      run: |
#        echo "OUTPUT_DATE=$(date +'%Y-%m-%d')" >> "${env:GITHUB_OUTPUT}"
#        echo "OUTPUT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> "${env:GITHUB_OUTPUT}"

#    - name: Show output date
#      id: echo-output-date
#      run: |
#        echo "${{steps.output-date.outputs.OUTPUT_DATE}}"
#        echo "${{steps.output-date.outputs.OUTPUT_DATETIME}}"

#    - name: Add MSBuild to PATH
#      id: msbuild-path
#      uses: microsoft/setup-msbuild@v1.1

    - name: Clone SDL repository
      id: clone-repository
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      working-directory: ${{github.workspace}}
      run: |
        git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/libsdl-org/SDL.git
        git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/libsdl-org/SDL_image.git
        git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/libsdl-org/SDL_mixer.git
        git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/libsdl-org/SDL_net.git
        git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/libsdl-org/SDL_ttf.git

    - name: Run external download
      id: run-external-download
      run: |
        ${{github.workspace}}/SDL_image/external/download.sh
        ${{github.workspace}}/SDL_mixer/external/download.sh
        ${{github.workspace}}/SDL_ttf/external/download.sh
      continue-on-error: true
    
    - name: Cmake SDL
      id: cmake-sdl
      run: |
        cmake -S ${{github.workspace}}/SDL -B ${{github.workspace}}/SDL/build
        cmake --build ${{github.workspace}}/SDL/build --config Release
        cmake --install ${{github.workspace}}/SDL/build --config Release
      continue-on-error: true

    - name: Cmake SDL_image
      id: cmake-sdl-image
      run: |
        cmake -S ${{github.workspace}}/SDL_image -B ${{github.workspace}}/SDL_image/build -DSDL3_DIR=${{github.workspace}}/SDL/build -DSDLIMAGE_AVIF=OFF
        cmake --build ${{github.workspace}}/SDL_image/build --config Release
        cmake --install ${{github.workspace}}/SDL_image/build --config Release
      continue-on-error: true

    - name: Cmake SDL_mixer
      id: cmake-sdl-mixer
      run: |
        cmake -S ${{github.workspace}}/SDL_mixer -B ${{github.workspace}}/SDL_mixer/build -DSDL3_DIR=${{github.workspace}}/SDL/build
        cmake --build ${{github.workspace}}/SDL_mixer/build --config Release
        cmake --install ${{github.workspace}}/SDL_mixer/build --config Release
      continue-on-error: true

    - name: Cmake SDL_net
      id: cmake-sdl-net
      run: |
        cmake -S ${{github.workspace}}/SDL_net -B ${{github.workspace}}/SDL_net/build -DSDL3_DIR=${{github.workspace}}/SDL/build
        cmake --build ${{github.workspace}}/SDL_net/build --config Release
        cmake --install ${{github.workspace}}/SDL_net/build --config Release
      continue-on-error: true

    - name: Cmake SDL_ttf
      id: cmake-sdl-ttf
      run: |
        cmake -S ${{github.workspace}}/SDL_ttf -B ${{github.workspace}}/SDL_ttf/build -DSDL3_DIR=${{github.workspace}}/SDL/build
        cmake --build ${{github.workspace}}/SDL_ttf/build --config Release
        cmake --install ${{github.workspace}}/SDL_ttf/build --config Release
      continue-on-error: true

    - name: Copy include
      id: copy-include
      run: |
        mkdir -p ${{github.workspace}}/dist/include/
        cp -r ${{github.workspace}}/SDL/include ${{github.workspace}}/dist/include/
        cp -r ${{github.workspace}}/SDL_image/include ${{github.workspace}}/dist/include/
        cp -r ${{github.workspace}}/SDL_mixer/include ${{github.workspace}}/dist/include/
        cp -r ${{github.workspace}}/SDL_ttf/include ${{github.workspace}}/dist/include/
        cp -r ${{github.workspace}}/SDL_net/include ${{github.workspace}}/dist/include/
      continue-on-error: true

    - name: Copy dll
      id: copy-dll
      run: |
        mkdir -p ${{github.workspace}}/dist/lib/x64/
        cp -r ${{github.workspace}}/SDL/build/Release ${{github.workspace}}/dist/lib/x64
        cp -r ${{github.workspace}}/SDL_image/build/Release ${{github.workspace}}/dist/lib/x64
        cp -r ${{github.workspace}}/SDL_mixer/build/Release ${{github.workspace}}/dist/lib/x64
        cp -r ${{github.workspace}}/SDL_net/build/Release ${{github.workspace}}/dist/lib/x64
        cp -r ${{github.workspace}}/SDL_ttf/build/Release ${{github.workspace}}/dist/lib/x64
      continue-on-error: true

    - name: Copy dll external x86
      id: copy-dll-external-x86
      run: |
        mkdir -p ${{github.workspace}}/dist/lib/x86/
        cp -r ${{github.workspace}}/SDL_image/VisualC/external/optional/x86 ${{github.workspace}}/dist/lib/x86
        cp -r ${{github.workspace}}/SDL_mixer/VisualC/external/optional/x86 ${{github.workspace}}/dist/lib/x86
      continue-on-error: true

    - name: Copy dll external x64
      id: copy-dll-external-x64
      run: |
        mkdir -p ${{github.workspace}}/dist/lib/x64/
        cp -r ${{github.workspace}}/SDL_image/VisualC/external/optional/x64 ${{github.workspace}}/dist/lib/x64
        cp -r ${{github.workspace}}/SDL_mixer/VisualC/external/optional/x64 ${{github.workspace}}/dist/lib/x64
      continue-on-error: true

#    - name: Copy LICENSE
#      id: copy-license
#      run: |
#        cp -r ${{github.workspace}}/SDL ${{github.workspace}}/dist/license/SDL LICENSE*.*
#        cp -r ${{github.workspace}}/SDL_image ${{github.workspace}}/dist/license/SDL_image LICENSE*.*
#        cp -r ${{github.workspace}}/SDL_mixer ${{github.workspace}}/dist/license/SDL_mixer LICENSE*.*
#        cp -r ${{github.workspace}}/SDL_net ${{github.workspace}}/dist/license/SDL_net LICENSE*.*
#        cp -r ${{github.workspace}}/SDL_ttf ${{github.workspace}}/dist/license/SDL_ttf LICENSE*.*
#        cp -r ${{github.workspace}}/SDL_image/VisualC/external/optional/x64 ${{github.workspace}}/dist/license/SDL_image LICENSE*.*
#        cp -r ${{github.workspace}}/SDL_mixer/VisualC/external/optional/x64 ${{github.workspace}}/dist/license/SDL_mixer LICENSE*.*
#        cp -r ${{github.workspace}}/SDL_ttf/VisualC/external/lib/x64 ${{github.workspace}}/dist/license/SDL_ttf LICENSE*.*
#      continue-on-error: true

#    - name: Zipping
#      id: zipping
#      run: powershell compress-archive ${{github.workspace}}/dist/* ${{github.workspace}}/SDL3-${{steps.output-date.outputs.OUTPUT_DATE}} -Force

#    - name: Archive production artifacts
#      id: artifact
#      uses: actions/upload-artifact@v4
#      with:
#        name: ${{steps.output-date.outputs.OUTPUT_DATE}}
#        path: ${{github.workspace}}/SDL3-${{steps.output-date.outputs.OUTPUT_DATE}}.zip

#    - name: Relase
#      id: release
#      env:
#        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#      run: |
#        gh release create ${{steps.output-date.outputs.OUTPUT_DATE}} --title ${{steps.output-date.outputs.OUTPUT_DATE}} --notes ""
#      continue-on-error: true
#
#    - name: Upload
#      id: upload
#      env:
#        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#      run: |
#        gh release upload ${{steps.output-date.outputs.OUTPUT_DATE}} ${{github.workspace}}/SDL3-${{steps.output-date.outputs.OUTPUT_DATE}}.zip --clobber

